package frc.robot.subsystems.swerve;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import javax.tools.JavaFileManager.Location;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.FieldCentric;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.pathfinding.LocalADStar;
import com.pathplanner.lib.pathfinding.Pathfinding;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.BooleanEntry;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Robot;
import frc.robot.constants.DriveConstants;
import frc.robot.constants.LocationConstants;
import frc.robot.constants.SwerveConstants.TunerSwerveDrivetrain;
import frc.robot.constants.TeleopConstants;
import frc.robot.utils.Container;
import frc.robot.utils.LimelightHelpers;
import frc.robot.utils.LocalADStarAK;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private Pigeon2 imu;
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
        private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private final SendableChooser<String> startPoseChooser = new SendableChooser<>();

    private SwerveRequest.FieldCentric driveRequest;
    private SwerveRequest.SwerveDriveBrake brakeRequest;
        private SwerveRequest.PointWheelsAt pointRequest;
    
        private double distanceToHub;
        private double xDistanceToHub;
        private double yDistanceToHub;
  private Field2d field = new Field2d();

      private NetworkTable llTable = NetworkTableInstance.getDefault().getTable("LL");
  private BooleanEntry llFixedEnabledEntry =
      llTable.getBooleanTopic("LL-Fixed_Enabled").getEntry(true);
  private BooleanEntry disabledLocoEnabledEntry =
      llTable.getBooleanTopic("DisabledLocoEnabled").getEntry(true);

        /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
        private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                null,        // Use default ramp rate (1 V/s)
                Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                null,        // Use default timeout (10 s)
                // Log state with SignalLogger class
                state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
            ),
            new SysIdRoutine.Mechanism(
                output -> setControl(m_translationCharacterization.withVolts(output)),
                null,
                this
            )
        );
    
        /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
        private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                null,        // Use default ramp rate (1 V/s)
                Volts.of(7), // Use dynamic voltage of 7 V
                null,        // Use default timeout (10 s)
                // Log state with SignalLogger class
                state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
            ),
            new SysIdRoutine.Mechanism(
                volts -> setControl(m_steerCharacterization.withVolts(volts)),
                null,
                this
            )
        );
    
        /*
         * SysId routine for characterizing rotation.
         * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
         * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
         */
        private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                /* This is in radians per second², but SysId only supports "volts per second" */
                Volts.of(Math.PI / 6).per(Second),
                /* This is in radians per second, but SysId only supports "volts" */
                Volts.of(Math.PI),
                null, // Use default timeout (10 s)
                // Log state with SignalLogger class
                state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
            ),
            new SysIdRoutine.Mechanism(
                output -> {
                    /* output is actually radians per second, but SysId only supports "volts" */
                    setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                    /* also log the requested output for SysId */
                    SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                },
                null,
                this
            )
        );
    
        /* The SysId routine to test */
        private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
         * @param modules               Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(drivetrainConstants, modules);
            imu = new Pigeon2(drivetrainConstants.Pigeon2Id,"rio");
            configureAutoBuilder();
            if (Utils.isSimulation()) {
                startSimThread();
            }
            setupDrivetrain();
    SmartDashboard.putData("Conf/Field", field);

        }
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            
            super(drivetrainConstants, odometryUpdateFrequency, modules);
    
            imu = new Pigeon2(drivetrainConstants.Pigeon2Id,"rio");
            configureAutoBuilder();
            if (Utils.isSimulation()) {
                startSimThread();
            }
            setupDrivetrain();
    SmartDashboard.putData("Conf/Field", field);

        }
    
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
            imu = new Pigeon2(drivetrainConstants.Pigeon2Id,"rio");
            configureAutoBuilder();
            if (Utils.isSimulation()) {
                startSimThread();
            }
            setupDrivetrain();
                SmartDashboard.putData("Conf/Field", field);
        }
    
        public Pigeon2 getGyro() {
            return imu;
        }
    
    
        /**
         * Returns a command that applies the specified control request to this swerve drivetrain.
         *
         * @param request Function returning the request to apply
         * @return Command to run
         */
        public Command applyRequest(Supplier<SwerveRequest> request) {
            return run(() -> this.setControl(request.get()));
        }
    
        /**
         * Runs the SysId Quasistatic test in the given direction for the routine
         * specified by {@link #m_sysIdRoutineToApply}.
         *
         * @param direction Direction of the SysId Quasistatic test
         * @return Command to run
         */
        public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
            return m_sysIdRoutineToApply.quasistatic(direction);
        }
    
        /**
         * Runs the SysId Dynamic test in the given direction for the routine
         * specified by {@link #m_sysIdRoutineToApply}.
         *
         * @param direction Direction of the SysId Dynamic test
         * @return Command to run
         */
        public Command sysIdDynamic(SysIdRoutine.Direction direction) {
            return m_sysIdRoutineToApply.dynamic(direction);
        }
    
        @Override
        public void periodic() {
            /*
             * Periodically try to apply the operator perspective.
             * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
             * This allows us to correct the perspective in case the robot code restarts mid-match.
             * Otherwise, only check and apply the operator perspective if the DS is disabled.
             * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
             */
            if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                DriverStation.getAlliance().ifPresent(allianceColor -> {
                    setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                            ? kRedAlliancePerspectiveRotation
                            : kBlueAlliancePerspectiveRotation
                    );
                    m_hasAppliedOperatorPerspective = true;
                });
                if (Robot.isReal()) visionPeriodic();
                field.setRobotPose(getPose());

            }
    
    
            if(Robot.isReal()) {
            if (DriverStation.getAlliance().get() == Alliance.Red) {
                distanceToHub = (LocationConstants.RED_HUB_AIM_POSE.getTranslation().getDistance(getPose().getTranslation()));
                xDistanceToHub = (Math.abs(LocationConstants.RED_HUB_AIM_POSE.getTranslation().getX() - getPose().getTranslation().getX()));
                yDistanceToHub = (Math.abs(LocationConstants.RED_HUB_AIM_POSE.getTranslation().getY() - getPose().getTranslation().getY()));
            } else {
                distanceToHub = (LocationConstants.BLUE_HUB_AIM_POSE.getTranslation().getDistance(getPose().getTranslation()));
                xDistanceToHub = (Math.abs(LocationConstants.BLUE_HUB_AIM_POSE.getTranslation().getX() - getPose().getTranslation().getX()));
                yDistanceToHub = (Math.abs(LocationConstants.BLUE_HUB_AIM_POSE.getTranslation().getY() - getPose().getTranslation().getY()));
            }
            } else {
                distanceToHub = (LocationConstants.RED_HUB_AIM_POSE.getTranslation().getDistance(getPose().getTranslation()));
                xDistanceToHub = (Math.abs(LocationConstants.RED_HUB_AIM_POSE.getTranslation().getX() - getPose().getTranslation().getX()));
                yDistanceToHub = (Math.abs(LocationConstants.RED_HUB_AIM_POSE.getTranslation().getY() - getPose().getTranslation().getY()));
            }
    
    
            updateStartConditions();
        }
    
        public double getDistanceToHub(){
            return distanceToHub;
        }
        public double getXDistanceToHub() {
            return xDistanceToHub;
        }
        public double getYDistanceToHub() {
            return xDistanceToHub;
        }
        public double getTangentToHub() {
            return yDistanceToHub/xDistanceToHub;
        }
        public double getThetaToHub() {
            return Math.atan2(xDistanceToHub, yDistanceToHub);
        }
    
        public Pose2d getPose() {
            return getSwerveDriveState().Pose;
        }
    
        public StatusSignal<Angle> getHeadingStatusSignalType(){
            return imu.getYaw();
        }
        
    
        public double getGyroHeading() {
            double rawYaw = getHeadingStatusSignalType().getValueAsDouble();
            double yawWrapped = rawYaw % 360;
            if (yawWrapped < 0){
                yawWrapped += 360;
            }
            return yawWrapped;
        }
    
        public void gyroReset() {
            this.seedFieldCentric();
            imu.reset();
        }
    
        private void startSimThread() {
            m_lastSimTime = Utils.getCurrentTimeSeconds();
    
            /* Run simulation at a faster rate so PID gains behave more reasonably */
            m_simNotifier = new Notifier(() -> {
                final double currentTime = Utils.getCurrentTimeSeconds();
                double deltaTime = currentTime - m_lastSimTime;
                m_lastSimTime = currentTime;
    
                /* use the measured time delta, get battery voltage from WPILib */
                updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
            m_simNotifier.startPeriodic(kSimLoopPeriod);
        }
    
        /**
         * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
         * while still accounting for measurement noise.
         *
         * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
         * @param timestampSeconds The timestamp of the vision measurement in seconds.
         */
        @Override
        public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
            super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
        }
    
        /**
         * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
         * while still accounting for measurement noise.
         * <p>
         * Note that the vision measurement standard deviations passed into this method
         * will continue to apply to future measurements until a subsequent call to
         * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
         *
         * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
         * @param timestampSeconds The timestamp of the vision measurement in seconds.
         * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
         *     in the form [x, y, theta]ᵀ, with units in meters and radians.
         */
        @Override
        public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs
        ) {
            super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
        }
    
        public SwerveDriveState getSwerveDriveState() {
            return super.getState();
        }
    
        public void configureAutoBuilder() {
            Pathfinding.setPathfinder(new LocalADStarAK());
            try {
                var config = RobotConfig.fromGUISettings();
                AutoBuilder.configure(
                    () -> getState().Pose,   // Supplier of current robot pose
                    this::resetPose,         // Consumer for seeding pose against auto
                    () -> getState().Speeds, // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                        m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                            .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                            .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                    ),
                    new PPHolonomicDriveController(
                        // PID constants for translation
                        new PIDConstants(DriveConstants.driveP, DriveConstants.driveI, DriveConstants.driveD),
                        // PID constants for rotation
                        new PIDConstants(DriveConstants.turnP, DriveConstants.turnI, DriveConstants.turnD)
                    ),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                    //TODO: bizde bu durum olmayabilir
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                    this // Subsystem for requirements
                );
            } catch (Exception ex) {
                DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
            }
        }
    
        
    
        /**
         * Return the pose at a given timestamp, if the buffer is not empty.
         *
         * @param timestampSeconds The timestamp of the pose in seconds.
         * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
         */
        @Override
        public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
            return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
        }
    
    
        private void setupDrivetrain(){
            driveRequest = new SwerveRequest.FieldCentric()
                .withDeadband(TeleopConstants.MaxSpeed * 0.1).withRotationalDeadband(TeleopConstants.MaxAngularRate * 0.1) // Add a 10% deadband
                .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
            brakeRequest = new SwerveRequest.SwerveDriveBrake();
        pointRequest = new SwerveRequest.PointWheelsAt();

        
        startPoseChooser.addOption("RIGHT", "RIGHT");
        startPoseChooser.addOption("MIDDLE", "MIDDLE");
        startPoseChooser.setDefaultOption("LEFT", "LEFT");
    
        SmartDashboard.putData("Conf/StartPoseChooser", startPoseChooser);
        setStartingPose();
    }

    private void setStartingPose() {
        if (DriverStation.isDisabled()){
            resetPose(Container.startPose);
        }
    }
    private void updateStartConditions()
    {
        if(DriverStation.isDisabled())
        {
            String selectedStartPose = startPoseChooser.getSelected();
            Pose2d selectedPose = LocationConstants.START_POSE_RED_LEFT; //Default
            if (Robot.isReal()) {
            if (DriverStation.getAlliance().get() == Alliance.Red) {
                switch (selectedStartPose) {
                    case "LEFT":
                        selectedPose = LocationConstants.START_POSE_RED_LEFT;
                        break;
                    case "MIDDLE":
                        selectedPose = LocationConstants.START_POSE_RED_MIDDLE;
                        break;
                    case "RIGHT":
                        selectedPose = LocationConstants.START_POSE_RED_RIGHT;
                        break;
                }
            } else {
                switch (selectedStartPose) {
                    case "LEFT":
                        selectedPose = LocationConstants.START_POSE_BLUE_LEFT;
                        break;
                    case "MIDDLE":
                        selectedPose = LocationConstants.START_POSE_BLUE_MIDDLE;
                        break;
                    case "RIGHT":
                        selectedPose = LocationConstants.START_POSE_BLUE_RIGHT;
                        break;
                }
                
            }} else {
                switch (selectedStartPose) {
                    case "LEFT":
                        selectedPose = LocationConstants.START_POSE_RED_LEFT;
                        break;
                    case "MIDDLE":
                        selectedPose = LocationConstants.START_POSE_RED_MIDDLE;
                        break;
                    case "RIGHT":
                        selectedPose = LocationConstants.START_POSE_RED_RIGHT;
                        break;
                }
            }
            resetPose(selectedPose);
        }
    }

    public Command teleopDriveCommand(CommandXboxController joystick) {
        return this.applyRequest(() ->
                        driveRequest.withVelocityX(joystick.getLeftY() * TeleopConstants.MaxSpeed) // Drive forward with negative Y (forward)
                            .withVelocityY(joystick.getLeftX() * TeleopConstants.MaxSpeed) // Drive left with negative X (left)
                            .withRotationalRate(-joystick.getRightX() * TeleopConstants.MaxAngularRate)// Drive counterclockwise with negative X (left)
                    );
    }
    public SwerveRequest.FieldCentric getDriveRequest() { return driveRequest; }
  public double getGyroRate() {
    return getState().Speeds.omegaRadiansPerSecond * (180.0 / Math.PI);
  }
  public double getHeading() {
    double yawDeg = getPose().getRotation().getDegrees() % 360;
    if (yawDeg < 0) {
      yawDeg += 360;
    }
    return yawDeg;
  }
    //Vision
      LimelightHelpers.IMUData imuData;
  private static final Matrix<N3, N1> MT2_VISION_STD_DEVS = VecBuilder.fill(.6, .6, 9999999);
  private static final Matrix<N3, N1> MT1_VISION_STD_DEVS = VecBuilder.fill(.5, .5, 9999999);
  private double tempRobotYaw = 0.0;
  private LimelightHelpers.PoseEstimate tempLimelightMeasurementFixed;
  private boolean tempDoRejectUpdate = false;
  private boolean tempDoRejectFixed = false;

  public void addVisionMeasurementMT2() {
    // Keep Limelight orientation aligned with drivetrain heading.
    tempRobotYaw = getHeading();
    LimelightHelpers.SetRobotOrientation("limelight", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);

    imuData = LimelightHelpers.getIMUData("limelight");

    tempLimelightMeasurementFixed =
        LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight");

    tempDoRejectUpdate = false;
    tempDoRejectFixed = false;

    if (Math.abs(getGyroRate()) > 360) {
      tempDoRejectUpdate = true;
    }

    // if(drivetrain.swerveDataSupplier().get().swerveControlState == SwerveState.AIMING)
    // doRejectUpdate = true;

    /*if (tempLimelightMeasurementTurret != null) {
      if (tempLimelightMeasurementTurret.tagCount == 0) {
        tempDoRejectTurret = true;
      }
      if (Math.abs(imuData.accelZ) > 120.0) {
        tempDoRejectTurret = true;
      }
    } else tempDoRejectTurret = true;*/

    if (tempLimelightMeasurementFixed != null) {
      if (tempLimelightMeasurementFixed.tagCount == 0) {
        tempDoRejectFixed = true;
      }
    } else tempDoRejectFixed = true;

    // Apply accepted measurements with conservative heading trust.
    if (!tempDoRejectUpdate) {

      if (!tempDoRejectFixed && llFixedEnabledEntry.get(true)) {
        setVisionMeasurementStdDevs(MT2_VISION_STD_DEVS);
        addVisionMeasurement(
            tempLimelightMeasurementFixed.pose, tempLimelightMeasurementFixed.timestampSeconds);
      }
    }
  }

  public void addVisionMeasurementMT1() {
    // Keep Limelight orientation aligned with drivetrain heading.
    tempRobotYaw = getHeading();
    LimelightHelpers.SetRobotOrientation("limelight", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);

    // Gather both camera estimates (legacy solve path).
    tempLimelightMeasurementFixed = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight");

    tempDoRejectUpdate = false;
    tempDoRejectFixed = false;

    if (Math.abs(getGyroRate()) > 360) {
      tempDoRejectUpdate = true;
    }

    if (tempLimelightMeasurementFixed != null) {
      if (tempLimelightMeasurementFixed.tagCount < 1) {
        tempDoRejectFixed = true;
      }
      if (tempLimelightMeasurementFixed.avgTagDist > 3.5) {
        tempDoRejectFixed = true;
      }
    } else tempDoRejectFixed = true;

    if (!tempDoRejectUpdate) {

      if (!tempDoRejectFixed && llFixedEnabledEntry.get(true)) {
        setVisionMeasurementStdDevs(MT1_VISION_STD_DEVS);
        addVisionMeasurement(
            tempLimelightMeasurementFixed.pose, tempLimelightMeasurementFixed.timestampSeconds);
      }
    }
  }

  public void resetWithMT1() {
    // Prefer fixed camera reset; fall back to turret camera if needed.
    tempRobotYaw = 0;

    tempLimelightMeasurementFixed = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight");

    if (tempLimelightMeasurementFixed != null && tempLimelightMeasurementFixed.tagCount > 0) {
      if (tempLimelightMeasurementFixed.avgTagDist < 3.0) {
        resetPose(tempLimelightMeasurementFixed.pose);
        tempRobotYaw = tempLimelightMeasurementFixed.pose.getRotation().getDegrees();
      }
    }

    LimelightHelpers.SetRobotOrientation("limelight", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
    LimelightHelpers.SetIMUMode("limelight", 1);
  }

    private boolean isMode1Set = false;
  private boolean isLLReady = false;

  public void disabledPeriodic() {
    // In disabled, optionally relocalize continuously for cleaner autonomous starts.
    isMode1Set = true;

    if (disabledLocoEnabledEntry.get(true)) {
      resetWithMT1();
    }
  }

  public void enabledPeriodic() {
    // On first enable after disabled, switch LL IMU mode for in-match tracking.
    if (!isLLReady && isMode1Set) {
      tempRobotYaw = getPose().getRotation().getDegrees();

      LimelightHelpers.SetRobotOrientation(
          "limelight", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
      LimelightHelpers.SetIMUMode("limelight", 0);
      isLLReady = true;
    }
    if (isLLReady) addVisionMeasurementMT2();
    }

      private boolean isEnabled = false;
  // Vision sampling: run vision-heavy work once every VISION_LOOPS scheduler loops
  private int visionLoopCounter = 0;
  private static final int VISION_LOOPS = 4; // ~10Hz at 20ms loop; tune as needed
  // Disabled relocalization can be expensive over NT; run at a lower cadence.
  private int disabledVisionLoopCounter = 0;
  private static final int DISABLED_VISION_LOOPS = 10; // ~5Hz at 20ms loop

  public void visionPeriodic() {
    boolean wasEnabled = isEnabled;
    if (DriverStation.isEnabled() && !isEnabled) {
      // rising edge: mark enabled
      isEnabled = true;
    }
    if (DriverStation.isDisabled() && isEnabled) {
      // falling edge: clear flags
      isEnabled = false;
      isLLReady = false;
      disabledVisionLoopCounter = DISABLED_VISION_LOOPS;
    }

    if (isEnabled) {
      if (!wasEnabled) {
        // Just became enabled — run the enabledPeriodic once immediately to initialize Limelight
        // state
        enabledPeriodic();
        visionLoopCounter = 0;
      } else {
        // Rate-limit expensive vision processing to reduce loop jitter.
        visionLoopCounter++;
        if (visionLoopCounter >= VISION_LOOPS) {
          visionLoopCounter = 0;
          enabledPeriodic();
        }
      }
    } else {
      // Disabled loop can be expensive due to relocalization + LL config writes.
      // Keep periodic lightweight by throttling to a slower cadence.
      disabledVisionLoopCounter++;
      if (disabledVisionLoopCounter >= DISABLED_VISION_LOOPS) {
        disabledVisionLoopCounter = 0;
        disabledPeriodic();
      }
    }
  }
}
